"""
Seed script for achievement badges.

Seeds all badge definitions into the ``badges`` table.
Run with:
    python scripts/seed_badges.py
"""

import asyncio
import sys
import os

# Allow importing app modules from the backend directory
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

from app.models.database import Badge, AsyncSessionLocal, engine, create_tables


BADGES = [
    # ── Hunt Milestones ────────────────────────────────────────────────────────
    {
        "badge_id": "B2FEDF50-DAE4-48D5-847D-966F94552CDA",
        "name": "First Strike",
        "description": "Log your very first metal detecting hunt.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 1},
        "points": 10,
        "rarity": "common",
    },
    {
        "badge_id": "E4701C4C-8126-4BE7-BAA2-91B76ACE0022",
        "name": "Trailblazer",
        "description": "Log 10 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 10},
        "points": 25,
        "rarity": "uncommon",
    },
    {
        "badge_id": "08CC5F51-5D6D-4CF9-97E0-4FE30C65EE5C",
        "name": "Quarter Century",
        "description": "Log 25 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 25},
        "points": 35,
        "rarity": "uncommon",
    },
    {
        "badge_id": "DB6EAF3C-374D-4F89-8844-8DEDFDD824E0",
        "name": "Field Veteran",
        "description": "Log 50 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 50},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "E6F0E042-9E9B-4BE5-972C-FBAB71BE989D",
        "name": "Century Detectorist",
        "description": "Log 100 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 100},
        "points": 100,
        "rarity": "epic",
    },
    {
        "badge_id": "08D32D67-7A74-4BBB-90AE-162B80E985A7",
        "name": "Seasoned Detectorist",
        "description": "Log 150 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 150},
        "points": 125,
        "rarity": "epic",
    },
    {
        "badge_id": "2CA081DD-E3C0-4121-8311-80129EA574A0",
        "name": "Quarter Thousand",
        "description": "Log 250 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 250},
        "points": 150,
        "rarity": "epic",
    },
    {
        "badge_id": "9994C625-AD5D-43C8-A1A4-7F044B7228AB",
        "name": "Master Detectorist",
        "description": "Log 500 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 500},
        "points": 250,
        "rarity": "legendary",
    },
    {
        "badge_id": "CC14F451-6FC9-4D04-87D5-2B6373B3EB95",
        "name": "Legend of the Fields",
        "description": "Log 750 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 750},
        "points": 300,
        "rarity": "legendary",
    },
    {
        "badge_id": "1310B568-3641-488E-B4AE-B8CF1B3E4348",
        "name": "Thousand Hunt Club",
        "description": "Log 1,000 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 1000},
        "points": 350,
        "rarity": "legendary",
    },
    {
        "badge_id": "AA79464B-FBD2-42F0-A00B-39F987EAF390",
        "name": "Elite Detectorist",
        "description": "Log 2,500 metal detecting hunts.",
        "category": "hunt_milestone",
        "criteria": {"type": "hunt_count", "threshold": 2500},
        "points": 500,
        "rarity": "legendary",
    },
    # ── Finds Milestones ───────────────────────────────────────────────────────
    {
        "badge_id": "0F708ADA-DB26-4ABB-9328-7A732ADEBA04",
        "name": "First Dig",
        "description": "Record your very first find.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 1},
        "points": 10,
        "rarity": "common",
    },
    {
        "badge_id": "0202D7C9-D71B-4159-AA06-5E8909AB1579",
        "name": "Lucky Strike",
        "description": "Record 50 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 50},
        "points": 30,
        "rarity": "uncommon",
    },
    {
        "badge_id": "513FE740-AC62-4911-B3B9-709AA727D595",
        "name": "Centurion",
        "description": "Record 100 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 100},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "A0160651-5B6F-40C8-A72D-C8C49796ED63",
        "name": "Gold Rush",
        "description": "Record 250 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 250},
        "points": 75,
        "rarity": "rare",
    },
    {
        "badge_id": "B069BF75-D426-48B8-8B9C-2542A9B8AB98",
        "name": "Five Hundred Club",
        "description": "Record 500 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 500},
        "points": 100,
        "rarity": "rare",
    },
    {
        "badge_id": "54BC557C-A1C3-44FE-9956-B192EE1E9DF6",
        "name": "Treasure Vault",
        "description": "Record 1,000 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 1000},
        "points": 200,
        "rarity": "legendary",
    },
    {
        "badge_id": "A047C73E-46A0-4B9B-A774-71834386F53E",
        "name": "Legendary Finder",
        "description": "Record 2,500 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 2500},
        "points": 250,
        "rarity": "legendary",
    },
    {
        "badge_id": "C0E12EBB-E225-4194-87AF-DE9764FF83B4",
        "name": "Grand Master Finder",
        "description": "Record 5,000 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 5000},
        "points": 400,
        "rarity": "legendary",
    },
    {
        "badge_id": "9D083A6D-2164-4CF9-B9DE-FD7807A75A6A",
        "name": "Pinnacle Collector",
        "description": "Record 10,000 total finds.",
        "category": "finds",
        "criteria": {"type": "finds_count", "threshold": 10000},
        "points": 500,
        "rarity": "legendary",
    },
    # ── Treasure Trove — Coins ─────────────────────────────────────────────────
    {
        "badge_id": "A1B2C3D4-E5F6-7890-ABCD-EF1234567890",
        "name": "Coin Collector",
        "description": "Add 50 coins to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "coin", "threshold": 50},
        "points": 60,
        "rarity": "rare",
    },
    {
        "badge_id": "E46CD796-E5BB-48DE-A3F6-9F9819ADC019",
        "name": "Coin Hoarder",
        "description": "Add 100 coins to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "coin", "threshold": 100},
        "points": 80,
        "rarity": "epic",
    },
    # ── Treasure Trove — Buttons ───────────────────────────────────────────────
    {
        "badge_id": "B2C3D4E5-F6A7-8901-BCDE-F12345678901",
        "name": "Button Box",
        "description": "Add 25 buttons to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "button", "threshold": 25},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "D1840574-3B84-4621-9602-5CC0A095E381",
        "name": "Button Baron",
        "description": "Add 50 buttons to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "button", "threshold": 50},
        "points": 70,
        "rarity": "epic",
    },
    # ── Treasure Trove — Bullets ───────────────────────────────────────────────
    {
        "badge_id": "C3D4E5F6-A7B8-9012-CDEF-123456789012",
        "name": "Lead Farmer",
        "description": "Add 50 bullets to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "bullet", "threshold": 50},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "0F5AE77F-8165-45F5-977B-2B12C29D6C75",
        "name": "Bullet Cache",
        "description": "Add 100 bullets to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "bullet", "threshold": 100},
        "points": 70,
        "rarity": "epic",
    },
    # ── Treasure Trove — Jewelry ───────────────────────────────────────────────
    {
        "badge_id": "D4E5F6A7-B8C9-0123-DEF0-234567890123",
        "name": "Jewelry Box",
        "description": "Add 10 jewelry items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "jewelry", "threshold": 10},
        "points": 70,
        "rarity": "epic",
    },
    {
        "badge_id": "FB3E90DF-3C93-4AF2-99BE-C8EF7F443600",
        "name": "Jewel Hunter",
        "description": "Add 20 jewelry items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "jewelry", "threshold": 20},
        "points": 90,
        "rarity": "epic",
    },
    # ── Treasure Trove — Buckles ───────────────────────────────────────────────
    {
        "badge_id": "E5F6A7B8-C9D0-1234-EF01-345678901234",
        "name": "Buckle Up",
        "description": "Add 15 buckles to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "buckle", "threshold": 15},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "79F9EB4B-7278-4905-B46F-3FD4696778D5",
        "name": "Buckle Bonanza",
        "description": "Add 30 buckles to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "buckle", "threshold": 30},
        "points": 70,
        "rarity": "epic",
    },
    # ── Treasure Trove — Tokens ────────────────────────────────────────────────
    {
        "badge_id": "2BF09FED-D947-48DD-988D-7ACEBB55EB69",
        "name": "Token Collector",
        "description": "Add 20 tokens to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "token", "threshold": 20},
        "points": 45,
        "rarity": "uncommon",
    },
    {
        "badge_id": "7490BFDE-231E-4A1B-9602-F8EC2F971B43",
        "name": "Token Hoarder",
        "description": "Add 40 tokens to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "token", "threshold": 40},
        "points": 65,
        "rarity": "rare",
    },
    # ── Treasure Trove — Relics ────────────────────────────────────────────────
    {
        "badge_id": "2D9B7BC9-64F3-4F23-B18C-35869DB60E1E",
        "name": "Relic Hunter",
        "description": "Add 30 relics to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "relic", "threshold": 30},
        "points": 60,
        "rarity": "rare",
    },
    {
        "badge_id": "8B75E001-50FD-467E-ABF0-1FF29ADA2430",
        "name": "Relic Keeper",
        "description": "Add 60 relics to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "relic", "threshold": 60},
        "points": 80,
        "rarity": "epic",
    },
    # ── Treasure Trove — Tools ─────────────────────────────────────────────────
    {
        "badge_id": "5EEF6215-08A5-4936-A58F-B8C48689FA6A",
        "name": "Tool Time",
        "description": "Add 15 tools to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "tool", "threshold": 15},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "700576FC-02A1-48DC-A733-3719166CB73F",
        "name": "Tool Collector",
        "description": "Add 30 tools to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "tool", "threshold": 30},
        "points": 60,
        "rarity": "rare",
    },
    # ── Treasure Trove — Keys ──────────────────────────────────────────────────
    {
        "badge_id": "AB6DF9CC-A90C-4CF2-9A99-2614AFA7AD6D",
        "name": "Key Master",
        "description": "Add 25 keys to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "key", "threshold": 25},
        "points": 45,
        "rarity": "uncommon",
    },
    {
        "badge_id": "FB00E77D-B31E-42C7-B418-8362A8D958B5",
        "name": "Key Keeper",
        "description": "Add 50 keys to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "key", "threshold": 50},
        "points": 65,
        "rarity": "rare",
    },
    # ── Treasure Trove — Rings ─────────────────────────────────────────────────
    {
        "badge_id": "DD0DA858-8A6A-4167-B50D-801A3BBBB35A",
        "name": "Ring Finder",
        "description": "Add 15 rings to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "ring", "threshold": 15},
        "points": 65,
        "rarity": "epic",
    },
    {
        "badge_id": "1E3C2B5A-4205-4576-AD11-DB9360E79BA7",
        "name": "Ring Royalty",
        "description": "Add 30 rings to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "ring", "threshold": 30},
        "points": 85,
        "rarity": "epic",
    },
    # ── Treasure Trove — Other Collection Types ────────────────────────────────
    {
        "badge_id": "3C261864-F1F1-4260-AFE1-B20143B6BFD5",
        "name": "Military Collector",
        "description": "Add 40 military items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "military", "threshold": 40},
        "points": 55,
        "rarity": "rare",
    },
    {
        "badge_id": "8498503B-1A85-41E2-B35E-5CB00B15447D",
        "name": "Religious Finds",
        "description": "Add 10 religious items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "religious", "threshold": 10},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "85461A82-856A-406A-8549-E61F8F03293B",
        "name": "Toy Box",
        "description": "Add 20 toys to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_type_count", "find_type": "toy", "threshold": 20},
        "points": 35,
        "rarity": "uncommon",
    },
    # ── Treasure Trove — Materials ─────────────────────────────────────────────
    {
        "badge_id": "061302AA-D444-4F8F-ADDC-983777155D9E",
        "name": "Silver Streak",
        "description": "Add 10 silver items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "silver", "threshold": 10},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "489167A5-79C2-4ABA-AA94-34D6B6654977",
        "name": "Copper King",
        "description": "Add 50 copper coins to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "copper", "threshold": 50},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "2BABCDAE-285C-4380-9187-08F46CAC6465",
        "name": "Iron Collection",
        "description": "Add 100 iron items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "iron", "threshold": 100},
        "points": 30,
        "rarity": "common",
    },
    {
        "badge_id": "0C9C9A13-D6C8-4E6F-B149-835DCD88FBF8",
        "name": "Brass Brigade",
        "description": "Add 25 brass items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "brass", "threshold": 25},
        "points": 35,
        "rarity": "uncommon",
    },
    {
        "badge_id": "0EC0559F-5F7C-4E01-A5A2-E616D85EE9F9",
        "name": "Gold Seeker",
        "description": "Add 5 gold items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "gold", "threshold": 5},
        "points": 100,
        "rarity": "legendary",
    },
    {
        "badge_id": "FFBFBBD5-330C-4526-B124-C227959DD0D1",
        "name": "Lead Hoarder",
        "description": "Add 100 lead items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "lead", "threshold": 100},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "CE9FF587-86CF-41F6-BD04-6EB50EEB1916",
        "name": "Bronze Age",
        "description": "Add 30 bronze items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "bronze", "threshold": 30},
        "points": 45,
        "rarity": "uncommon",
    },
    {
        "badge_id": "20794163-42DD-47AE-9037-F85AB11DE52B",
        "name": "Aluminum Hunter",
        "description": "Add 50 aluminum items to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "collection_material_count", "material": "aluminum", "threshold": 50},
        "points": 25,
        "rarity": "common",
    },
    {
        "badge_id": "E467EA86-6364-41C0-920E-8407151EF265",
        "name": "Material Master",
        "description": "Add items from 5 different materials to your collection.",
        "category": "treasure_trove",
        "criteria": {"type": "material_diversity", "threshold": 5},
        "points": 100,
        "rarity": "epic",
    },
    # ── Treasure Trove — Cache ─────────────────────────────────────────────────
    {
        "badge_id": "ED63E475-083A-4FA3-9760-32DBCF698142",
        "name": "Cache Discovery",
        "description": "Discover a cache with 5 or more items.",
        "category": "treasure_trove",
        "criteria": {"type": "cache_discovery", "threshold": 5},
        "points": 80,
        "rarity": "epic",
    },
    # ── Historic Sites ────────────────────────────────────────────────────────
    {
        "badge_id": "E883C4AC-C15B-4E59-97D3-598D42EC9719",
        "name": "Battlefield Relic Hunter",
        "description": "Detect at a historic battle site.",
        "category": "sites",
        "criteria": {"type": "site_type", "site_type": "battle"},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "8B8C83CF-AA55-4E8F-BC58-F9F8E08B4FBA",
        "name": "Boomtown Prospector",
        "description": "Detect at a historic mining town.",
        "category": "sites",
        "criteria": {"type": "site_type", "site_type": "mine"},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "29EC28F1-A34A-41E3-B0D6-FFF06FBC6394",
        "name": "Stagecoach Chaser",
        "description": "Detect at a historic stagecoach stop.",
        "category": "sites",
        "criteria": {"type": "site_type", "site_type": "stagecoach_stop"},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "346E9135-22D6-4197-9281-D939E8F2DC51",
        "name": "Pony Express Rider",
        "description": "Detect along a historic Pony Express route.",
        "category": "sites",
        "criteria": {"type": "site_type", "site_type": "pony_express"},
        "points": 60,
        "rarity": "epic",
    },
    {
        "badge_id": "FF2299B5-FAD9-4EED-9352-DD8F9D607174",
        "name": "Mission Seeker",
        "description": "Detect near a historic mission.",
        "category": "sites",
        "criteria": {"type": "site_type", "site_type": "mission"},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "FC0C795B-E848-48D2-88A1-D69F7B3E3432",
        "name": "Route Seeker",
        "description": "Hunt within 100 meters of a historic trail.",
        "category": "sites",
        "criteria": {"type": "linear_feature_proximity", "feature_type": "trail", "distance_meters": 100},
        "points": 40,
        "rarity": "rare",
    },
    {
        "badge_id": "4F84DD14-3200-4DA0-96C1-2FA51A591DEE",
        "name": "Site Connoisseur",
        "description": "Hunt at 5 different types of historic sites.",
        "category": "sites",
        "criteria": {"type": "site_diversity", "threshold": 5},
        "points": 75,
        "rarity": "epic",
    },
    {
        "badge_id": "D3F56B4F-AA82-44F3-9671-093EFDDCBC2C",
        "name": "Battlefield Expert",
        "description": "Detect at 5 different historic battle sites.",
        "category": "sites",
        "criteria": {"type": "site_type_count", "site_type": "battle", "threshold": 5},
        "points": 70,
        "rarity": "epic",
    },
    {
        "badge_id": "EA59EC34-632C-4502-9553-39CAE437D14B",
        "name": "Mine Explorer",
        "description": "Detect at 10 different historic mining sites.",
        "category": "sites",
        "criteria": {"type": "site_type_count", "site_type": "mine", "threshold": 10},
        "points": 60,
        "rarity": "rare",
    },
    {
        "badge_id": "91A5D2A4-1EFD-4FF0-AA7D-9C53E5DA54AD",
        "name": "Mission Pilgrim",
        "description": "Detect at 5 different historic mission sites.",
        "category": "sites",
        "criteria": {"type": "site_type_count", "site_type": "mission", "threshold": 5},
        "points": 65,
        "rarity": "rare",
    },
    # ── Geographic ────────────────────────────────────────────────────────────
    {
        "badge_id": "B4ED4716-472A-423E-804D-143690D66C30",
        "name": "Multi-State Hunter",
        "description": "Log hunts in 3 or more different states.",
        "category": "geographic",
        "criteria": {"type": "states_visited", "threshold": 3},
        "points": 60,
        "rarity": "rare",
    },
    {
        "badge_id": "CC4BFB0F-CD70-4204-ADFA-3FFF6BF5F2E0",
        "name": "Five State Explorer",
        "description": "Log hunts in 5 or more different states.",
        "category": "geographic",
        "criteria": {"type": "states_visited", "threshold": 5},
        "points": 80,
        "rarity": "rare",
    },
    {
        "badge_id": "043AAF14-75DB-4335-A7B0-AD5B6D063181",
        "name": "Ten State Adventurer",
        "description": "Log hunts in 10 or more different states.",
        "category": "geographic",
        "criteria": {"type": "states_visited", "threshold": 10},
        "points": 100,
        "rarity": "epic",
    },
    {
        "badge_id": "69785B32-BA05-4611-9F67-C8B427FF327A",
        "name": "Nation Wide",
        "description": "Log hunts in 25 or more different states.",
        "category": "geographic",
        "criteria": {"type": "states_visited", "threshold": 25},
        "points": 200,
        "rarity": "legendary",
    },
    {
        "badge_id": "334144B5-4393-4FCA-96F8-169C4E571ADF",
        "name": "Coast to Coast",
        "description": "Log hunts in both coastal regions (Atlantic and Pacific).",
        "category": "geographic",
        "criteria": {"type": "coastal_coverage", "threshold": 2},
        "points": 150,
        "rarity": "legendary",
    },
    {
        "badge_id": "853EAE0F-736C-4CAA-B20A-3EC222CE482F",
        "name": "Distance Hunter",
        "description": "Travel 500 km or more to metal detecting sites.",
        "category": "geographic",
        "criteria": {"type": "max_distance_traveled", "threshold": 500},
        "points": 75,
        "rarity": "epic",
    },
    {
        "badge_id": "638383BA-B794-41CE-BEC9-F8B6D4EB96AE",
        "name": "Long Haul Hunter",
        "description": "Travel 1,000 km or more to metal detecting sites.",
        "category": "geographic",
        "criteria": {"type": "max_distance_traveled", "threshold": 1000},
        "points": 100,
        "rarity": "epic",
    },
    {
        "badge_id": "BD2EEC79-E66D-4B67-B558-7AE288CFD347",
        "name": "Weekend Warrior",
        "description": "Log hunts on consecutive weekend days.",
        "category": "geographic",
        "criteria": {"type": "weekend_streak", "threshold": 2},
        "points": 30,
        "rarity": "uncommon",
    },
    {
        "badge_id": "EFEECA8E-48D2-47A5-BB32-5055E480C14D",
        "name": "Seasonal Hunter",
        "description": "Log hunts during all four seasons in a single year.",
        "category": "geographic",
        "criteria": {"type": "seasonal_coverage", "threshold": 4},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "54F64423-B215-479E-897B-28C78EE4FC2E",
        "name": "Year-Long Detectorist",
        "description": "Log at least one hunt every month for an entire year.",
        "category": "geographic",
        "criteria": {"type": "monthly_streak", "threshold": 12},
        "points": 100,
        "rarity": "epic",
    },
    # ── Time & Dedication — Streaks ───────────────────────────────────────────
    {
        "badge_id": "CE0834BB-A6BD-427E-8AAC-BFAE5E544D60",
        "name": "Streak Starter",
        "description": "Log hunts on 30 consecutive days.",
        "category": "geographic",
        "criteria": {"type": "daily_streak", "threshold": 30},
        "points": 75,
        "rarity": "rare",
    },
    {
        "badge_id": "69EF7BB4-3106-458A-9510-3CA6BCCC4D09",
        "name": "Iron Will",
        "description": "Log hunts on 100 consecutive days.",
        "category": "geographic",
        "criteria": {"type": "daily_streak", "threshold": 100},
        "points": 150,
        "rarity": "epic",
    },
    {
        "badge_id": "2A8F0503-DF7F-410D-9570-9977A29500F1",
        "name": "Daily Grind",
        "description": "Log hunts on 365 consecutive days.",
        "category": "geographic",
        "criteria": {"type": "daily_streak", "threshold": 365},
        "points": 300,
        "rarity": "legendary",
    },
    # ── Community Contribution ────────────────────────────────────────────────
    {
        "badge_id": "D764C958-9847-45D8-BEB6-3611D2545D47",
        "name": "Map Maker",
        "description": "Submit your first location to the Aurik database.",
        "category": "community",
        "criteria": {"type": "submission_count", "threshold": 1},
        "points": 20,
        "rarity": "uncommon",
    },
    {
        "badge_id": "DA31CC83-B2E7-4A1C-9705-658B35DE1C98",
        "name": "History Keeper",
        "description": "Have 25 submissions approved by the community.",
        "category": "community",
        "criteria": {"type": "approved_submissions", "threshold": 25},
        "points": 75,
        "rarity": "rare",
    },
    {
        "badge_id": "AF7AEB2C-6F9C-4734-A537-12C0610CF212",
        "name": "Community Historian",
        "description": "Have 100 submissions approved by the community.",
        "category": "community",
        "criteria": {"type": "approved_submissions", "threshold": 100},
        "points": 200,
        "rarity": "epic",
    },
    # ── Social ────────────────────────────────────────────────────────────────
    {
        "badge_id": "94297D70-0BF8-4913-ADB8-073E6672EB85",
        "name": "First Shout",
        "description": "Post your first comment or share a find with the community.",
        "category": "social",
        "criteria": {"type": "comment_count", "threshold": 1},
        "points": 10,
        "rarity": "common",
    },
    {
        "badge_id": "8773F5EF-1AE8-4212-8191-479E2E78ABA8",
        "name": "Great Find!",
        "description": "Receive 10 likes or positive reactions on a shared find.",
        "category": "social",
        "criteria": {"type": "likes_count", "threshold": 10},
        "points": 25,
        "rarity": "uncommon",
    },
    {
        "badge_id": "D9A62F2B-C821-4D87-AB96-1448AD741E13",
        "name": "Crowd Favorite",
        "description": "Have one of your finds receive 50+ likes from the community.",
        "category": "social",
        "criteria": {"type": "single_post_likes", "threshold": 50},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "36FF0A6C-A14B-49C1-9183-C66A02581A26",
        "name": "Community Pillar",
        "description": "Reach 100+ total likes across all your shared content.",
        "category": "social",
        "criteria": {"type": "total_likes", "threshold": 100},
        "points": 75,
        "rarity": "epic",
    },
    # ── Special Event / Dedication ────────────────────────────────────────────
    {
        "badge_id": "8EDC9DC3-02FE-4E5F-9B75-DBD39ECB2527",
        "name": "Night Hunter",
        "description": "Log a hunt after sunset.",
        "category": "special_event",
        "criteria": {"type": "time_of_day", "time_range": "night"},
        "points": 25,
        "rarity": "uncommon",
    },
    {
        "badge_id": "3FB6A091-CD5D-4455-8463-C2C21FDCA7D8",
        "name": "Dawn Patrol",
        "description": "Log a hunt at sunrise.",
        "category": "special_event",
        "criteria": {"type": "time_of_day", "time_range": "dawn"},
        "points": 25,
        "rarity": "uncommon",
    },
    {
        "badge_id": "86923B0E-13EA-4171-B779-9464C2B67CA2",
        "name": "Storm Chaser",
        "description": "Log a hunt during or immediately after a storm.",
        "category": "special_event",
        "criteria": {"type": "weather_condition", "condition": "storm"},
        "points": 40,
        "rarity": "rare",
    },
    {
        "badge_id": "D3DE9936-C1D5-48AD-BF33-1C0E40C314C3",
        "name": "First Snow",
        "description": "Log a hunt during the first snowfall of the year.",
        "category": "special_event",
        "criteria": {"type": "weather_condition", "condition": "first_snow"},
        "points": 30,
        "rarity": "rare",
    },
    {
        "badge_id": "C636E674-F8EB-48B6-913A-8ADDC228455D",
        "name": "Early Bird",
        "description": "Log 10 hunts before 8am.",
        "category": "dedication",
        "criteria": {"type": "early_hunts", "threshold": 10, "time_before": "08:00"},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "45234C5B-7974-4861-B3DA-895C7ACB8E92",
        "name": "Moonlighter",
        "description": "Log 10 hunts after 8pm.",
        "category": "dedication",
        "criteria": {"type": "late_hunts", "threshold": 10, "time_after": "20:00"},
        "points": 40,
        "rarity": "uncommon",
    },
    {
        "badge_id": "4D4DA825-21C5-44B2-A09E-C9163BEA30AA",
        "name": "Pinpoint Perfect",
        "description": "Log 10 hunts with pinpoint accuracy (all finds recorded with exact coordinates).",
        "category": "dedication",
        "criteria": {"type": "pinpoint_accuracy", "threshold": 10},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "CD78884E-28E4-4AF5-B3B6-D4B2169D20ED",
        "name": "Holiday Hunter",
        "description": "Log a hunt on a major holiday.",
        "category": "special_event",
        "criteria": {"type": "holiday_hunt", "threshold": 1},
        "points": 30,
        "rarity": "uncommon",
    },
    {
        "badge_id": "A3736528-B4E0-4A43-ACBD-89D53E082CEF",
        "name": "Midnight Detectorist",
        "description": "Log a hunt at exactly midnight.",
        "category": "special_event",
        "criteria": {"type": "time_of_day", "time_range": "midnight"},
        "points": 35,
        "rarity": "uncommon",
    },
    # ── Conservation ──────────────────────────────────────────────────────────
    {
        "badge_id": "133A322B-ECBA-4BCA-9A2C-1BBF64BE34D9",
        "name": "Trash Collector",
        "description": "Remove 100 pieces of trash while metal detecting.",
        "category": "conservation",
        "criteria": {"type": "trash_collected", "threshold": 100},
        "points": 50,
        "rarity": "rare",
    },
    {
        "badge_id": "1FA4510C-7ECF-44F1-9783-C646414662DF",
        "name": "Leave No Trace",
        "description": "Fill in 50 dig holes properly.",
        "category": "conservation",
        "criteria": {"type": "holes_filled", "threshold": 50},
        "points": 60,
        "rarity": "rare",
    },
]


async def seed() -> None:
    """Ensure the schema is up-to-date and upsert all badge rows."""
    await create_tables()

    async with AsyncSessionLocal() as session:
        from sqlalchemy import select

        existing_result = await session.execute(select(Badge))
        existing_map = {row.badge_id.upper(): row for row in existing_result.scalars().all()}

        inserted = 0
        updated = 0
        for data in BADGES:
            badge_id_upper = data["badge_id"].upper()
            if badge_id_upper in existing_map:
                badge = existing_map[badge_id_upper]
                changed = (
                    badge.name != data["name"]
                    or badge.description != data["description"]
                    or badge.category != data["category"]
                    or badge.criteria != data["criteria"]
                    or badge.points != data["points"]
                    or badge.rarity != data["rarity"]
                )
                if changed:
                    badge.name = data["name"]
                    badge.description = data["description"]
                    badge.category = data["category"]
                    badge.criteria = data["criteria"]
                    badge.points = data["points"]
                    badge.rarity = data["rarity"]
                    updated += 1
                    print(f"  update {data['name']}")
                else:
                    print(f"  skip  {data['name']} (no changes)")
            else:
                badge = Badge(
                    badge_id=data["badge_id"],
                    name=data["name"],
                    description=data["description"],
                    category=data["category"],
                    criteria=data["criteria"],
                    points=data["points"],
                    rarity=data["rarity"],
                )
                session.add(badge)
                inserted += 1
                print(f"  insert {data['name']}")

        await session.commit()
        print(f"\nDone. {inserted} badge(s) inserted, {updated} updated, {len(BADGES) - inserted - updated} skipped.")


if __name__ == "__main__":
    asyncio.run(seed())
